# Install Apache webserver in RedHat/Aamzon Linux VM
---

- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Install httpd
      yum: name=httpd state=present
      when: ansible_os_family == "RedHat"

    - name: Enable HTTPD service
      service: name=httpd enabled=yes state=started
      when: ansible_os_family == "RedHat"
